name: CI/CD Pipeline

on:
  pull_request:
    branches: [master]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.github/BRANCH_PROTECTION_SETUP.md'
      - '.github/CI_CD_README.md'
  push:
    branches: [master]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.github/BRANCH_PROTECTION_SETUP.md'
      - '.github/CI_CD_README.md'

env:
  NODE_VERSION: '20'

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint:eslint

      - name: Check code formatting
        run: npm run lint:check

      - name: Run tests
        run: npm run test:run

      - name: Build project
        run: npm run build

  type-check:
    name: Type Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Type check
        run: npm run check
